spring:
  application:
    name: api-gateway

  # spring cloud api gateway setup
  cloud:
    gateway:
      routes:
        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/api/v1/orders/**
          filters:
            - StripPrefix=2
        - id: inventory-service
          uri: lb://INVENTORY-SERVICE
          predicates:
            - Path=/api/v1/inventory/**
          filters:
            - StripPrefix=2
            - AddRequestHeader=x-my-header, PRANAV
            # - RedirectTo=302, http://google.com
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
